import { Component } from '@angular/core';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.css'],
})
export class BlogComponent {
  blogList: any = [
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-1.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-2.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-3.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-1.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-2.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-3.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-2.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-1.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-3.jpg',
    },
    {
      icon1: 'bi bi-person me-2',
      icon2: 'bi bi-bookmarks me-2',
      day: '01',
      month: 'Jan',
      year: '2045',
      text: 'Magna sea dolor ipsum amet lorem eos',
      img: '../../../assets/images/blog-2.jpg',
    },
  ];
}
